// SPDX-License-Identifier: AGPL-3.0-or-later

//! Keyboard-shortcuts window for the GTK front-end.
//!
//! Per `IMPLEMENTATION_PLAN_04_GTK.md` §"Keyboard Shortcuts window"
//! and `DESIGN.md` §7, the primary menu's "Keyboard Shortcuts" entry
//! and the GNOME-canonical `Ctrl+?` accelerator open a
//! `gtk::ShortcutsWindow` listing every window-wide accelerator
//! currently registered through
//! [`crate::app::model::format_app_window_accelerator_bindings`].
//!
//! The window is constructed from a single `gtk::Builder` XML
//! template generated by [`format_app_shortcuts_window_xml`]. Each
//! `GtkShortcutsShortcut` row sources its accelerator and title
//! from the same pinned `format_app_*_accelerator` /
//! `format_app_*_label` / `format_app_*_tooltip` helpers that drive
//! the header-bar `+` button, the primary menu, and the
//! `gio::Application::set_accels_for_action` wiring — so the wording
//! and key spelling stay in lockstep across every surface.
//!
//! Pure-logic helpers (the entry table and the XML template
//! generator) live here so the `tests/` integration tests can pin
//! them without spinning up libadwaita.

use relm4::gtk;

use crate::app::model::{
    format_app_add_button_accelerator, format_app_add_button_tooltip,
    format_app_menu_keyboard_shortcuts_accelerator, format_app_menu_keyboard_shortcuts_label,
    format_app_menu_preferences_accelerator, format_app_menu_preferences_label,
    format_app_menu_quit_accelerator, format_app_menu_quit_label,
    format_app_search_focus_accelerator, format_app_search_focus_label,
};

/// Fixed title of the single `GtkShortcutsGroup` inside the
/// generated `GtkShortcutsWindow`.
///
/// Returns the static label `"General"` — the wording GNOME apps
/// conventionally use for the only group on a single-group
/// shortcuts window (no per-area sub-grouping yet because every
/// pinned accelerator is window-wide rather than scoped to a sub-
/// view). Pinning the title here keeps the
/// [`format_app_shortcuts_window_xml`] generator a single
/// iteration over [`format_app_shortcuts_window_entries`] without
/// hand-spelling the section/group label inside the XML template.
///
/// Pure — returns a `'static str` without allocating.
#[must_use]
pub fn format_app_shortcuts_window_section_title() -> &'static str {
    "General"
}

/// Ordered `(accelerator, title)` pairs the `GtkShortcutsWindow`
/// renders, one per row, in the single `GtkShortcutsGroup`.
///
/// Each pair sources both fields from `paladin-gtk`'s existing
/// pinned helpers:
///
/// * `(<Control>n, "Add account")` — same accelerator as
///   [`format_app_add_button_accelerator`] and same wording as
///   [`format_app_add_button_tooltip`], so the row mirrors the
///   header-bar `+` button surface.
/// * `(slash <Control>k, "Search accounts")` —
///   [`format_app_search_focus_accelerator`] /
///   [`format_app_search_focus_label`] mirror the window-level
///   focus-search accelerator wired by
///   [`crate::app::model::wire_app_window_search_focus_controller`].
///   The `accelerator` property accepts a space-separated list, so
///   the single row renders both bindings together — matching how
///   the helper itself treats them as interchangeable shortcuts.
/// * `(<Control>comma, "Preferences")` —
///   [`format_app_menu_preferences_accelerator`] /
///   [`format_app_menu_preferences_label`] mirror the primary
///   menu's Preferences entry.
/// * `(<Control>question, "Keyboard Shortcuts")` — the entry for
///   this very window, sourced from
///   [`format_app_menu_keyboard_shortcuts_accelerator`] /
///   [`format_app_menu_keyboard_shortcuts_label`].
/// * `(<Control>q, "Quit")` — [`format_app_menu_quit_accelerator`] /
///   [`format_app_menu_quit_label`] mirror the primary menu's Quit
///   entry.
///
/// Display order is the most-frequent-use flow (Add → Search →
/// Preferences → Keyboard Shortcuts → Quit) and is intentionally
/// distinct from the
/// [`crate::app::model::format_app_window_accelerator_bindings`]
/// iteration order (which is Add → Quit → Preferences →
/// Keyboard Shortcuts) — the bindings array is sized to keep
/// `set_accels_for_action` wiring stable, while this array is
/// sized for human reading. The Search row is intentionally absent
/// from `format_app_window_accelerator_bindings` because it is not
/// a `gio::SimpleAction` accelerator (it lives behind a window-
/// level `gtk::EventControllerKey` so a focused entry gets first
/// crack at the keystroke and inline `/`-typing into any text
/// entry still works).
///
/// Pure — returns an owned array of two-tuples without
/// allocating.
#[must_use]
pub fn format_app_shortcuts_window_entries() -> [(&'static str, &'static str); 5] {
    [
        (
            format_app_add_button_accelerator(),
            format_app_add_button_tooltip(),
        ),
        (
            format_app_search_focus_accelerator(),
            format_app_search_focus_label(),
        ),
        (
            format_app_menu_preferences_accelerator(),
            format_app_menu_preferences_label(),
        ),
        (
            format_app_menu_keyboard_shortcuts_accelerator(),
            format_app_menu_keyboard_shortcuts_label(),
        ),
        (
            format_app_menu_quit_accelerator(),
            format_app_menu_quit_label(),
        ),
    ]
}

/// Generate the `gtk::Builder` XML template the
/// [`build_app_shortcuts_window`] sibling feeds into
/// `Builder::from_string`.
///
/// Wraps a single `GtkShortcutsSection` containing one
/// `GtkShortcutsGroup` (title from
/// [`format_app_shortcuts_window_section_title`]) whose children
/// are one `GtkShortcutsShortcut` per
/// [`format_app_shortcuts_window_entries`] tuple. Every accelerator
/// and title is XML-escaped (`<` / `>` / `&` / `"` / `'`) so that
/// accelerator strings like `<Control>n` survive the round-trip
/// through `gtk::Builder` without truncation or angle-bracket
/// parse errors.
///
/// The XML uses a fixed `id="shortcuts_window"` on the root
/// `GtkShortcutsWindow` object so [`build_app_shortcuts_window`]
/// can extract the typed widget by name.
///
/// Pure — allocates a fresh `String` on each call; safe to call
/// from tests without a GTK display.
#[must_use]
pub fn format_app_shortcuts_window_xml() -> String {
    let mut xml = String::new();
    xml.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    xml.push_str("<interface>\n");
    xml.push_str("  <object class=\"GtkShortcutsWindow\" id=\"shortcuts_window\">\n");
    xml.push_str("    <property name=\"modal\">true</property>\n");
    xml.push_str("    <child>\n");
    xml.push_str("      <object class=\"GtkShortcutsSection\">\n");
    xml.push_str("        <property name=\"section-name\">main</property>\n");
    xml.push_str("        <child>\n");
    xml.push_str("          <object class=\"GtkShortcutsGroup\">\n");
    xml.push_str("            <property name=\"title\">");
    xml.push_str(&xml_escape(format_app_shortcuts_window_section_title()));
    xml.push_str("</property>\n");
    for (accel, title) in format_app_shortcuts_window_entries() {
        xml.push_str("            <child>\n");
        xml.push_str("              <object class=\"GtkShortcutsShortcut\">\n");
        xml.push_str("                <property name=\"accelerator\">");
        xml.push_str(&xml_escape(accel));
        xml.push_str("</property>\n");
        xml.push_str("                <property name=\"title\" translatable=\"yes\">");
        xml.push_str(&xml_escape(title));
        xml.push_str("</property>\n");
        xml.push_str("              </object>\n");
        xml.push_str("            </child>\n");
    }
    xml.push_str("          </object>\n");
    xml.push_str("        </child>\n");
    xml.push_str("      </object>\n");
    xml.push_str("    </child>\n");
    xml.push_str("  </object>\n");
    xml.push_str("</interface>\n");
    xml
}

/// XML-escape the five characters that have special meaning inside
/// element text and attribute values.
///
/// Necessary because every accelerator string emitted by
/// [`format_app_shortcuts_window_entries`] embeds the literal `<`
/// and `>` characters around the modifier name (e.g.
/// `<Control>n`); without escaping, `gtk::Builder` would fail to
/// parse the template.
#[must_use]
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            other => out.push(other),
        }
    }
    out
}

/// Construct a fresh `gtk::ShortcutsWindow` from the pinned
/// [`format_app_shortcuts_window_xml`] template.
///
/// Mirrors `crate::app::model::build_app_about_dialog` on the
/// About-dialog surface: the widget is rebuilt on every
/// invocation (no shared mutable state) so the
/// `AppMsg::OpenKeyboardShortcuts` handler can present a fresh
/// window each time without tracking ownership through `AppModel`.
///
/// Requires a live GTK type system (`gtk::init` or `relm4::main`
/// must have run); panics on a builder failure so a regression
/// in the XML template fails loudly during a smoke test rather
/// than silently surfacing an empty window.
#[must_use]
pub fn build_app_shortcuts_window() -> gtk::ShortcutsWindow {
    let builder = gtk::Builder::from_string(&format_app_shortcuts_window_xml());
    builder
        .object::<gtk::ShortcutsWindow>("shortcuts_window")
        .expect("shortcuts_window XML must yield a GtkShortcutsWindow")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_app_shortcuts_window_section_title_returns_general() {
        assert_eq!(format_app_shortcuts_window_section_title(), "General");
    }

    #[test]
    fn format_app_shortcuts_window_entries_lists_five_rows_in_display_order() {
        let entries = format_app_shortcuts_window_entries();
        assert_eq!(entries.len(), 5);
        assert_eq!(
            entries[0],
            (
                format_app_add_button_accelerator(),
                format_app_add_button_tooltip(),
            )
        );
        assert_eq!(
            entries[1],
            (
                format_app_search_focus_accelerator(),
                format_app_search_focus_label(),
            )
        );
        assert_eq!(
            entries[2],
            (
                format_app_menu_preferences_accelerator(),
                format_app_menu_preferences_label(),
            )
        );
        assert_eq!(
            entries[3],
            (
                format_app_menu_keyboard_shortcuts_accelerator(),
                format_app_menu_keyboard_shortcuts_label(),
            )
        );
        assert_eq!(
            entries[4],
            (
                format_app_menu_quit_accelerator(),
                format_app_menu_quit_label(),
            )
        );
    }

    #[test]
    fn format_app_shortcuts_window_xml_starts_with_xml_declaration() {
        let xml = format_app_shortcuts_window_xml();
        assert!(xml.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"));
    }

    #[test]
    fn format_app_shortcuts_window_xml_declares_shortcuts_window_with_pinned_id() {
        let xml = format_app_shortcuts_window_xml();
        assert!(xml.contains("<object class=\"GtkShortcutsWindow\" id=\"shortcuts_window\">"));
    }

    #[test]
    fn format_app_shortcuts_window_xml_contains_one_section_and_one_group() {
        let xml = format_app_shortcuts_window_xml();
        assert_eq!(
            xml.matches("<object class=\"GtkShortcutsSection\">")
                .count(),
            1
        );
        assert_eq!(
            xml.matches("<object class=\"GtkShortcutsGroup\">").count(),
            1
        );
    }

    #[test]
    fn format_app_shortcuts_window_xml_includes_section_title() {
        let xml = format_app_shortcuts_window_xml();
        let needle = format!(
            "<property name=\"title\">{}</property>",
            format_app_shortcuts_window_section_title()
        );
        assert!(xml.contains(&needle), "missing section title: {xml}");
    }

    #[test]
    fn format_app_shortcuts_window_xml_contains_one_shortcut_per_entry() {
        let xml = format_app_shortcuts_window_xml();
        let entries = format_app_shortcuts_window_entries();
        assert_eq!(
            xml.matches("<object class=\"GtkShortcutsShortcut\">")
                .count(),
            entries.len()
        );
    }

    #[test]
    fn format_app_shortcuts_window_xml_xml_escapes_every_accelerator() {
        let xml = format_app_shortcuts_window_xml();
        // Every accelerator is wrapped in `<Modifier>key`; the `<` and `>`
        // must survive XML escaping as `&lt;` / `&gt;` so `gtk::Builder`
        // can parse the template.
        for (accel, _title) in format_app_shortcuts_window_entries() {
            let escaped = xml_escape(accel);
            assert!(
                xml.contains(&escaped),
                "expected escaped accelerator `{escaped}` (from `{accel}`) in XML: {xml}"
            );
            assert!(
                !xml.contains(&format!(">{accel}<")),
                "unescaped accelerator `{accel}` leaked into XML: {xml}"
            );
        }
    }

    #[test]
    fn format_app_shortcuts_window_xml_emits_every_pinned_title() {
        let xml = format_app_shortcuts_window_xml();
        for (_accel, title) in format_app_shortcuts_window_entries() {
            let escaped = xml_escape(title);
            assert!(
                xml.contains(&escaped),
                "expected title `{escaped}` in XML: {xml}"
            );
        }
    }

    #[test]
    fn xml_escape_escapes_all_five_special_characters() {
        assert_eq!(xml_escape("<"), "&lt;");
        assert_eq!(xml_escape(">"), "&gt;");
        assert_eq!(xml_escape("&"), "&amp;");
        assert_eq!(xml_escape("\""), "&quot;");
        assert_eq!(xml_escape("'"), "&apos;");
        assert_eq!(xml_escape("<Control>n"), "&lt;Control&gt;n");
        assert_eq!(xml_escape("plain"), "plain");
    }
}
