// SPDX-License-Identifier: AGPL-3.0-or-later

//! `AppState` — the TUI's top-level state machine — plus the pure
//! startup-decision functions that map `inspect` / `open` outcomes
//! onto initial states.
//!
//! See `DESIGN.md` §6 and `IMPLEMENTATION_PLAN_03_TUI.md`
//! "Startup / vault modes" + "Auto-lock (per §6)".

use std::path::{Path, PathBuf};
use std::time::Instant;

use paladin_core::{
    format_unsafe_permissions, AccountId, ClipboardClearToken, IdlePolicy, PaladinError, Store,
    Vault, VaultLock, VaultStatus,
};
use secrecy::SecretString;
use zeroize::Zeroizing;

use crate::prompt::PassphraseBuffer;

/// A clipboard auto-clear scheduled by an earlier copy effect and
/// awaiting either its wake-deadline (at which point the bytes are
/// wiped if they still match the system clipboard) or a stale-token
/// supersession.
///
/// Held on [`AppState::Unlocked`] while the user is active and on
/// [`AppState::Locked`] when an idle-expiry transition arrives before
/// the wake fires — per `IMPLEMENTATION_PLAN_03_TUI.md`
/// "Auto-lock (per §6)": *"A clipboard auto-clear timer scheduled
/// before lock survives lock and still fires only-if-unchanged."*
///
/// `value` is the bytes that were written to the clipboard; the
/// reducer compares them to the current clipboard contents via
/// [`paladin_core::ClipboardClearPolicy::should_clear`] when the wake
/// event arrives so a later external copy is preserved. The bytes are
/// non-secret-token-bearing on their own but reflect a code that was
/// just exposed to the user, so the same zeroization discipline as
/// other typed buffers applies — the field is wrapped in
/// [`Zeroizing<Vec<u8>>`] so `Drop` wipes the bytes in place before
/// the backing allocation is freed (covers the "after the clear
/// attempt" path when the executor consumes
/// [`Effect::ClearClipboard`] and the "supersession drop" path when
/// a fresher copy replaces the pending slot).
#[derive(Debug)]
pub struct PendingClipboardClear {
    /// Monotonic token returned by
    /// [`paladin_core::ClipboardClearPolicy::schedule`]. A later
    /// schedule on the same vault settings supersedes this one.
    pub token: ClipboardClearToken,
    /// The bytes the copy effect wrote to the clipboard. Compared
    /// byte-equal against the current clipboard contents when the
    /// wake fires; only-if-unchanged. Wrapped in [`Zeroizing`] so the
    /// bytes are wiped on drop.
    pub value: Zeroizing<Vec<u8>>,
    /// Monotonic wake-deadline; the timer thread sleeps until this
    /// instant and then sends an `AppEvent::ClipboardClear`.
    pub deadline: Instant,
}

/// An open HOTP reveal window: a code generated by `Vault::hotp_advance`
/// being shown to the user until either
/// [`paladin_core::HOTP_REVEAL_SECS`] elapses or `n` advances the
/// counter again.
///
/// Held on [`AppState::Unlocked`] only. Dropped on the
/// `Unlocked → Locked` auto-lock transition alongside the
/// `Vault` / `Store` per `IMPLEMENTATION_PLAN_03_TUI.md`
/// "Auto-lock (per §6)": *"Locking discards the Vault / Store, open
/// HOTP reveal windows, the search query, and any modal while
/// retaining the resolved vault path for the next unlock attempt."*
///
/// `code` is a recently displayed OTP and is held in
/// [`secrecy::SecretString`] so its bytes zeroize on drop; the full
/// zeroize-on-expiry / replacement / lock coverage rides on the
/// "Sensitive UI buffers" slice when the HOTP-reveal effect lands.
#[derive(Debug)]
pub struct HotpReveal {
    /// The account whose code is being revealed.
    pub account_id: AccountId,
    /// The counter value that produced the visible `code`; shown in
    /// place of the next-counter prompt until the deadline fires.
    pub counter_used: u64,
    /// The displayed code. Zeroizes on drop via
    /// [`secrecy::SecretString`].
    pub code: SecretString,
    /// Monotonic reveal-expiry returned by
    /// [`paladin_core::hotp_reveal_deadline`]; on each Tick the
    /// reducer compares this against `monotonic` and closes the
    /// reveal when expired.
    pub deadline: Instant,
}

/// A bottom-bar status message shown on the list view.
///
/// Set by actions that need to surface a short, non-modal message —
/// e.g. pressing `n` / `r` / `R` (and later `Enter`) with no account
/// selected per `IMPLEMENTATION_PLAN_03_TUI.md` "Focus model" — and
/// cleared on the `Unlocked → Locked` auto-lock transition alongside
/// the `Vault` / `Store` (by variant change). Replacement is
/// last-write-wins: a fresh status-line update overwrites any
/// existing one without preserving history.
///
/// Only the `Error` variant lands at this slice; the `Confirmation`
/// variant used by successful modal outcomes per the plan's
/// "Status-line states" list arrives alongside the corresponding
/// modal-effect slices.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StatusLine {
    /// An action was rejected without changing visible state — e.g.
    /// `n` / `r` / `R` with no account selected. The string is
    /// non-secret prose suitable for verbatim rendering on the bottom
    /// status bar.
    Error(String),
    /// A modal action succeeded and the reducer closed the modal.
    /// Per `IMPLEMENTATION_PLAN_03_TUI.md` "Modals (per §6)" >
    /// "Successful modal outcomes": *"manual Add, URI Add, Remove,
    /// Rename, Export, Passphrase, and Settings close the modal and
    /// publish a status-line confirmation."* The string is
    /// non-secret prose (no OTP digits, no passphrase bytes) built
    /// from the post-save vault state so it matches what a follow-up
    /// `list` would show.
    Confirmation(String),
}

/// Status-line error string surfaced when `n`, `r`, `R`, or (when
/// bound) `Enter` is pressed on Unlocked with `selected = None`. Per
/// `IMPLEMENTATION_PLAN_03_TUI.md` "Focus model": *"With no
/// selection, `Enter`, `n`, `r`, and `R` produce a status-line 'no
/// account selected' error and no effect."*
pub const NO_ACCOUNT_SELECTED: &str = "no account selected";

/// Status-line error string surfaced when an
/// [`crate::app::event::Effect::CopyCode`] effect fails its clipboard
/// write. Per `IMPLEMENTATION_PLAN_03_TUI.md` "Effect errors":
/// *"Copy: show a status-line error if clipboard write fails; do not
/// schedule auto-clear."* The wording mirrors the §5
/// `clipboard_write_failed` envelope key the CLI uses on its failure
/// path so all three front ends surface a recognizable phrase for
/// the same condition.
pub const CLIPBOARD_WRITE_FAILED: &str = "clipboard write failed";

/// A pending vim chord leader on the list view.
///
/// Set by the first press of a chord leader key and cleared by the
/// matching second press (which also commits the chord's action), by
/// any non-matching key, by a focus change, by a modal open, by `Esc`,
/// or by the `Unlocked → Locked` auto-lock transition (which drops
/// the field alongside the `Vault` / `Store`). Per
/// `IMPLEMENTATION_PLAN_03_TUI.md` "Layout (per §6)" the chord uses
/// vim's `nottimeout` semantics: there is no time-based clear; only
/// the next keypress can commit or break it.
///
/// `G` is the leader for the `gg` jump-to-first chord — the vim
/// mirror of `Home`. `Z` is the leader for the `zz` recenter
/// chord — the vim viewport-center command. A first press of either
/// key sets its pending leader and clears any other pending leader,
/// so `g` after `z` and `z` after `g` restart cleanly rather than
/// committing a mixed chord.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChordLeader {
    /// Lower-case `g` — leader for `gg` (jump-to-first).
    G,
    /// Lower-case `z` — leader for `zz` (recenter viewport on the
    /// selected row).
    Z,
}

/// Which area of the main list view currently captures input.
///
/// Per `IMPLEMENTATION_PLAN_03_TUI.md` "Focus model": focus
/// alternates between the search bar and the account list. On
/// list-view entry the focus starts on the account list so
/// navigation keys engage without a focus-toggle press; `/` focuses
/// the search bar, `Esc` returns focus to the list (also clearing
/// the search query), and `Tab` / `Shift-Tab` cycle between them
/// once the search-focus payload (text editing, focus-aware key
/// routing) lands. This slice introduces only the enum and the
/// `focus` slot so subsequent slices can wire the keybindings; on
/// the `Unlocked → Locked` auto-lock transition the focus slot is
/// discarded alongside the `Vault` / `Store` (by the variant
/// change), and re-entering Unlocked re-seeds `Focus::List` per the
/// "On list-view entry, focus starts on the account list" rule.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Focus {
    /// The account list captures input (selection movement, action
    /// keys like `a` / `r` / `n` / `Enter`, vim navigation chords).
    /// Default on every Unlocked-entry path.
    List,
    /// The search bar captures input (incremental query editing).
    /// List navigation keys (`↑` / `↓` / `PgUp` / `PgDn` / `Home` /
    /// `End` / `Ctrl-U` / `Ctrl-D` / `Ctrl-F` / `Ctrl-B`) still pass
    /// through to the list per the §6 / "Focus model" pass-through
    /// rule once that slice lands; bare-letter vim keys (`j` / `k`
    /// / `g` / `G` / `z`) and the action letters are consumed by
    /// the search field as text input.
    Search,
}

/// State for the Remove modal.
///
/// Per `IMPLEMENTATION_PLAN_03_TUI.md` "Modals (per §6)" > Remove: a
/// confirmation gate for removing the selected account. The
/// `account_id` is snapshotted when the modal opens so a subsequent
/// selection / search-filter change does not redirect the remove
/// mid-confirm; the submit path passes `account_id` straight through
/// to `Vault::remove` inside `Vault::mutate_and_save`.
///
/// [`Default`] yields a freshly generated [`AccountId`] sentinel so
/// existing reducer tests that match on the variant discriminant can
/// construct a placeholder without reaching into the vault.
/// Production code never relies on [`Default`] — the reducer's
/// modal-open path always populates `account_id` from the selected
/// account.
#[derive(Debug, Default)]
pub struct RemoveModal {
    /// Account being removed. Snapshotted at modal open time.
    pub account_id: AccountId,
    /// Inline save error from the most recent submit attempt, if any.
    /// Rendered through
    /// [`render_error_message`](crate::app::state::render_error_message)
    /// so the surfaced wording matches the rest of the TUI's error
    /// surface. The success / save-error rollback wiring lands
    /// alongside the `EffectResult::Remove` slice.
    pub error: Option<String>,
}

/// State for the Rename modal.
///
/// Per `IMPLEMENTATION_PLAN_03_TUI.md` "Modals (per §6)" > Rename:
/// *"single text field pre-populated with the selected account's
/// current label."* The `account_id` is snapshotted when the modal
/// opens so a subsequent selection / search-filter change does not
/// redirect the rename mid-edit; the submit path passes
/// `account_id` straight through to `Vault::rename` inside
/// `Vault::mutate_and_save`.
///
/// [`Default`] yields an empty draft and a freshly generated
/// [`AccountId`] sentinel so existing reducer tests that match on
/// the variant discriminant can construct a placeholder without
/// reaching into the vault. Production code never relies on
/// [`Default`] — the reducer's modal-open path always populates the
/// fields from the selected account.
#[derive(Debug, Default)]
pub struct RenameModal {
    /// Account whose label is being edited. Snapshotted at modal
    /// open time.
    pub account_id: AccountId,
    /// Working label buffer. Initialized to the selected account's
    /// current label at open time and updated by text-field editing.
    /// Cleared on submit / cancel / modal close / auto-lock alongside
    /// the rest of the modal-local state.
    pub draft: String,
    /// Inline validation / save error from the most recent submit
    /// attempt, if any. Rendered through
    /// [`render_error_message`](crate::app::state::render_error_message)
    /// so the surfaced wording matches the rest of the TUI's error
    /// surface. Subsequent edits clear this slot so the user sees
    /// they are re-trying, and a successful submit transitions
    /// through `EffectResult::Rename` (the success / save-error
    /// rollback wiring lands alongside that slice).
    pub error: Option<String>,
}

/// State for the Settings modal.
///
/// Per `IMPLEMENTATION_PLAN_03_TUI.md` "Modals (per §6)" > Settings:
/// *"toggles for `auto_lock.enabled` and `clipboard.clear_enabled`,
/// spinners for `auto_lock.timeout_secs` and `clipboard.clear_secs`.
/// … The modal accumulates pending edits in modal-local state and
/// only commits on Confirm: pending values are applied through the
/// same setters (`set_auto_lock_*`, `set_clipboard_clear_*`) inside
/// a single `Vault::mutate_and_save` transaction."*
///
/// The four fields are snapshotted from the live
/// [`paladin_core::VaultSettings`] when the modal opens; subsequent
/// edits stay modal-local until Confirm so `Esc` can discard them
/// without invoking any setter or save. Pre-commit save failures
/// restore the prior snapshot per the plan's "Effect errors" >
/// "Add / remove / rename / settings saves" section; the
/// success / save-error rollback wiring lands alongside the
/// Settings effect slice.
///
/// [`Default`] yields the same shape that `SettingsModal::default()`
/// would produce against a brand-new vault: both toggles off and the
/// minimum allowed spinner values per the shared core bounds. It
/// exists so existing reducer tests that match on the modal
/// discriminant can construct a placeholder without reaching into
/// the vault — production code never relies on it, because the
/// reducer's modal-open path always populates the fields from the
/// live vault settings.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SettingsModal {
    /// Pending `auto_lock.enabled` value. Snapshotted from
    /// [`paladin_core::VaultSettings::auto_lock_enabled`] at modal
    /// open time and edited modal-locally until Confirm.
    pub auto_lock_enabled: bool,
    /// Pending `auto_lock.timeout_secs` value. Clamped on edit to
    /// [`paladin_core::AUTO_LOCK_SECS_MIN`]..=[`paladin_core::AUTO_LOCK_SECS_MAX`]
    /// per the plan's "Modals (per §6)" > Settings spinner-bounds
    /// rule; the controls clamp before submit so the core setter
    /// rejection path stays a defensive backstop.
    pub auto_lock_timeout_secs: u32,
    /// Pending `clipboard.clear_enabled` value. Snapshotted from
    /// [`paladin_core::VaultSettings::clipboard_clear_enabled`] at
    /// modal open time and edited modal-locally until Confirm.
    pub clipboard_clear_enabled: bool,
    /// Pending `clipboard.clear_secs` value. Clamped on edit to
    /// [`paladin_core::CLIPBOARD_CLEAR_SECS_MIN`]..=[`paladin_core::CLIPBOARD_CLEAR_SECS_MAX`].
    pub clipboard_clear_secs: u32,
    /// Inline validation / save error from the most recent submit
    /// attempt, if any. Rendered through
    /// [`render_error_message`](crate::app::state::render_error_message)
    /// so the surfaced wording matches the rest of the TUI's error
    /// surface. Subsequent edits clear this slot so the user sees
    /// they are re-trying, and a successful submit transitions
    /// through `EffectResult::Settings` (the success / save-error
    /// rollback wiring lands alongside that slice).
    pub error: Option<String>,
}

/// An open modal dialog over the main list view.
///
/// Discarded on the `Unlocked → Locked` auto-lock transition
/// alongside the `Vault` / `Store`, search query, and HOTP reveal
/// window per `IMPLEMENTATION_PLAN_03_TUI.md` "Auto-lock (per §6)":
/// *"Locking discards the Vault / Store, open HOTP reveal windows,
/// the search query, and any modal while retaining the resolved
/// vault path for the next unlock attempt."*
///
/// Variant payloads (form fields, segmented selectors, zeroizing
/// passphrase buffers for the `Passphrase` / `Import` / `Export`
/// flows, post-success counts panels) land alongside each modal's
/// effect-wiring slice. The seven variants mirror the modals
/// enumerated in `IMPLEMENTATION_PLAN_03_TUI.md` "Modals (per §6)".
#[derive(Debug)]
pub enum Modal {
    /// Add an account — manual / `otpauth://` URI / clipboard-QR.
    Add,
    /// Confirm removal of the selected account.
    Remove(RemoveModal),
    /// Rename the selected account.
    Rename(RenameModal),
    /// Import an existing vault export (Paladin, Aegis, Google
    /// Authenticator).
    Import,
    /// Export the current vault (plaintext or twice-confirmed
    /// encrypted bundle).
    Export,
    /// Passphrase set / change / remove sub-flow.
    Passphrase,
    /// Settings: auto-lock and clipboard-clear toggles + timeouts.
    Settings(SettingsModal),
}

/// Top-level UI state.
///
/// Variants other than [`AppState::Unlocked`] are deliberately
/// `Vault`/`Store`-free so the TUI cannot mutate vault data from
/// non-unlocked screens (per the plan's "non-mutating missing-vault /
/// startup-error" guarantee).
///
/// The `Unlocked` variant intentionally owns the live `Vault`, `Store`,
/// and per-screen UI slots (search, idle deadline, pending clipboard
/// clear, open HOTP reveal, open modal) so save-bearing effects can
/// call `Vault::mutate_and_save` / `Vault::hotp_advance` directly
/// without indirection. `AppState` is a singleton on the run loop's
/// stack, not stored in a `Vec`, so the variant-size disparity has no
/// allocator/cache impact in practice; the resulting
/// `clippy::large_enum_variant` warning is therefore allowed at the
/// enum level rather than each large field being boxed.
#[derive(Debug)]
#[allow(clippy::large_enum_variant)]
pub enum AppState {
    /// Vault file does not exist; the TUI shows a non-mutating
    /// guidance screen telling the user to run `paladin init`.
    /// v0.1 TUI does not create vaults.
    MissingVault {
        /// The vault path that was inspected.
        path: PathBuf,
    },

    /// Encrypted vault: the unlock screen is shown and the user is
    /// prompted for the passphrase inside the TUI. A
    /// `decrypt_failed` from a previous attempt is held in `error`
    /// for inline display; every other `open` error replaces this
    /// state with [`AppState::StartupError`]. Typed passphrase bytes
    /// live in `passphrase`, a zeroizing buffer cleared on submit per
    /// `IMPLEMENTATION_PLAN_03_TUI.md` "Tests > Sensitive UI buffers".
    Unlock {
        /// The vault path being unlocked.
        path: PathBuf,
        /// Inline error (most recently `decrypt_failed`), if any.
        error: Option<String>,
        /// Typed passphrase characters; zeroized on submit, cancel,
        /// modal close, and auto-lock.
        passphrase: PassphraseBuffer,
    },

    /// Auto-locked: an encrypted vault that was previously unlocked
    /// but has timed out per the auto-lock idle policy. Keeps only
    /// the resolved path plus pending clipboard-clear state needed
    /// for re-unlock and scheduled clear; the previous `Vault`,
    /// `Store`, cached key, and any modal-local secret state are
    /// discarded.
    Locked {
        /// The vault path; same as the previously unlocked state's.
        path: PathBuf,
        /// Clipboard auto-clear that was scheduled while the vault
        /// was still unlocked. Carried across the
        /// `Unlocked → Locked` transition so the timer thread's
        /// `AppEvent::ClipboardClear` wake still finds a target
        /// pending state. Per `IMPLEMENTATION_PLAN_03_TUI.md`
        /// "Auto-lock (per §6)": *"A clipboard auto-clear timer
        /// scheduled before lock survives lock and still fires
        /// only-if-unchanged."*
        pending_clipboard_clear: Option<PendingClipboardClear>,
    },

    /// Unlocked: the main list view is active. Owns the `Vault` and
    /// `Store` so save-bearing effects can call
    /// `Vault::mutate_and_save`, `Vault::hotp_advance`, and
    /// passphrase-transition methods directly.
    Unlocked {
        /// The vault path the `Store` reads/writes.
        path: PathBuf,
        /// The decrypted in-memory vault.
        vault: Vault,
        /// Persistence handle for the vault file.
        store: Store,
        /// Active search-bar text used to filter the visible
        /// account list. Empty when no filter is set. Discarded on
        /// auto-lock alongside the `Vault` / `Store` per
        /// `IMPLEMENTATION_PLAN_03_TUI.md` "Auto-lock (per §6)":
        /// "the search query is cleared". Held in plain `String`
        /// because issuer / label text is non-secret (DESIGN §5);
        /// only secrets live in zeroizing storage.
        search_query: String,
        /// Auto-lock idle deadline (monotonic clock).
        ///
        /// `Some(now + timeout)` when
        /// [`paladin_core::IdlePolicy::should_arm`] holds for the
        /// current vault (encrypted **and** `auto_lock_enabled`);
        /// `None` otherwise — plaintext vaults always stay `None`
        /// per the §6 / §7 plaintext-no-op rule, and encrypted
        /// vaults with auto-lock disabled also stay `None`.
        ///
        /// Re-set on every `AppEvent::Input` and checked against
        /// monotonic `Tick` instants for the `Locked` transition.
        /// See `IMPLEMENTATION_PLAN_03_TUI.md` "Auto-lock (per §6)".
        idle_deadline: Option<Instant>,
        /// Clipboard auto-clear that was scheduled by an earlier
        /// copy effect and is still waiting for its wake-deadline.
        /// On the `Unlocked → Locked` transition this field moves
        /// onto [`AppState::Locked`] verbatim so the timer thread's
        /// wake event can still find pending state to act on. See
        /// `IMPLEMENTATION_PLAN_03_TUI.md` "Auto-lock (per §6)".
        pending_clipboard_clear: Option<PendingClipboardClear>,
        /// Open HOTP reveal window, if the user pressed `n` recently
        /// enough that the deadline returned by
        /// [`paladin_core::hotp_reveal_deadline`] has not yet
        /// elapsed. Discarded on the `Unlocked → Locked` transition
        /// alongside the `Vault` / `Store` per
        /// `IMPLEMENTATION_PLAN_03_TUI.md` "Auto-lock (per §6)":
        /// "Locking discards the Vault / Store, open HOTP reveal
        /// windows, the search query, and any modal …".
        hotp_reveal: Option<HotpReveal>,
        /// Open modal dialog, if any. Discarded on the
        /// `Unlocked → Locked` transition alongside the
        /// `Vault` / `Store` per `IMPLEMENTATION_PLAN_03_TUI.md`
        /// "Auto-lock (per §6)" — modal-local zeroizing buffers
        /// (e.g. the Passphrase modal's typed bytes) zeroize on drop
        /// as their payloads land in later slices.
        modal: Option<Modal>,
        /// Currently selected account in the list view, or `None`
        /// when the filtered set is empty.
        ///
        /// On Unlocked entry the previous selection is `None`, so the
        /// initial seed follows [`paladin_core::select_after_filter`]
        /// for `prev = None` and the empty-search filtered set
        /// (`Vault::iter()` in insertion order): the first account
        /// when one exists, `None` when the vault is empty. List
        /// navigation, search filter changes, add / remove / rename,
        /// and import outcomes update this field through the
        /// reducer; the `Unlocked → Locked` transition drops it
        /// alongside the `Vault` / `Store`.
        selected: Option<AccountId>,
        /// Pending two-press vim chord leader, if the most recent
        /// list-focus keystroke was a chord leader (e.g. lower-case
        /// `g` for the `gg` jump-to-first chord). `None` when no
        /// chord is in flight.
        ///
        /// Set by the chord leader keystroke, cleared by the
        /// matching second press (which also commits the chord's
        /// action), by any non-matching key, by a focus change to
        /// the search bar, by a modal open, by `Esc`, or by the
        /// `Unlocked → Locked` auto-lock transition (which drops the
        /// field alongside the `Vault` / `Store`). No time-based
        /// clear — vim's `nottimeout` semantics.
        pending_chord_leader: Option<ChordLeader>,
        /// Number of visible list rows in the current terminal
        /// viewport. Used by page / half-page navigation
        /// (`PgUp` / `PgDn` / `Ctrl-B` / `Ctrl-F` / `Ctrl-U` /
        /// `Ctrl-D`) to compute step sizes, and by the `zz`
        /// recenter chord to keep the selected row in the middle of
        /// the viewport. Seeded to `0` on every `Unlocked` entry;
        /// the production run loop replaces it with the real
        /// terminal height through the resize-driven viewport
        /// slice (not yet implemented) before the first draw. A
        /// `0` height makes page / half-page navigation a silent
        /// no-op, which keeps reducer-only unit tests deterministic
        /// until the resize handler lands.
        viewport_height: u16,
        /// Index of the first row of the filtered list rendered at
        /// the top of the viewport (insertion-order position
        /// inside `Vault::iter()` until the search-focus slice
        /// lands, then the filtered set). Mutated by the `zz`
        /// recenter chord to
        /// `sel_pos.saturating_sub(viewport_height / 2)`, so the
        /// selected row sits in the middle of the viewport. Seeded
        /// to `0` on every `Unlocked` entry; the resize-driven
        /// viewport slice and an auto-scroll "keep selection
        /// visible" pass land later, so page / half-page / arrow
        /// navigation does not touch this field at this slice —
        /// only `zz` commits to it. With `viewport_height = 0`,
        /// `selected = None`, or an empty vault, `zz` is a silent
        /// no-op and the field stays unchanged.
        viewport_offset: u16,
        /// Which area of the main list view captures keystrokes.
        ///
        /// Seeded to [`Focus::List`] on every Unlocked-entry path
        /// per the `IMPLEMENTATION_PLAN_03_TUI.md` "Focus model"
        /// rule *"On list-view entry, focus starts on the account
        /// list"*. The keybindings that move focus to the search
        /// bar (`/`), cycle focus (`Tab` / `Shift-Tab`), and return
        /// focus to the list while clearing the query (`Esc`) land
        /// in subsequent slices. On the `Unlocked → Locked`
        /// auto-lock transition the field is discarded alongside
        /// the `Vault` / `Store` (by variant change) and re-seeded
        /// to `Focus::List` whenever Unlocked is re-entered.
        focus: Focus,
        /// Bottom-bar status message, if any. `None` on Unlocked
        /// entry; set by selection-gated action keys (`n` / `r` /
        /// `R`) when `selected` is `None` per the
        /// `IMPLEMENTATION_PLAN_03_TUI.md` "Focus model" rule, and
        /// (in later slices) by modal-success confirmations and
        /// other rejected actions. Replacement is last-write-wins.
        /// Dropped on the `Unlocked → Locked` auto-lock transition
        /// alongside the `Vault` / `Store` (by variant change).
        status_line: Option<StatusLine>,
        /// Whether the read-only Help overlay is currently visible.
        ///
        /// Per `IMPLEMENTATION_PLAN_03_TUI.md` "Help overlay":
        /// *"`?` from list focus opens a read-only Help overlay
        /// listing every keybinding from the table below; `Esc`
        /// closes the overlay and restores list focus. The overlay
        /// has no inputs and never mutates vault state."*
        ///
        /// `?` opens the overlay only when `modal` is `None`,
        /// `focus` is [`Focus::List`], and this flag is `false`.
        /// While the flag is `true`, the only key that has any
        /// effect is `Esc` (close); every other key is a silent
        /// no-op so the overlay is genuinely read-only. The flag
        /// is dropped on the `Unlocked → Locked` auto-lock
        /// transition alongside the `Vault` / `Store` (by variant
        /// change) and re-seeded to `false` whenever Unlocked is
        /// re-entered.
        help_open: bool,
    },

    /// Non-mutating startup-error screen. Used when vault-path
    /// resolution fails or `inspect` / `open` returns anything other
    /// than `decrypt_failed`. Quits on `Esc` / `q` / `Ctrl-C`.
    StartupError {
        /// Vault path, if it was resolved before the failure.
        /// `None` if `default_vault_path` itself failed.
        path: Option<PathBuf>,
        /// Pre-rendered error text. `unsafe_permissions` uses the
        /// `Some(text)` from
        /// [`paladin_core::format_unsafe_permissions`] verbatim so
        /// all front ends share identical wording.
        message: String,
    },
}

/// Map a `paladin_core::inspect` result onto the corresponding initial
/// [`AppState`].
///
/// Returns `None` for [`VaultStatus::Plaintext`]: the caller must
/// follow up with `Store::open(path, VaultLock::Plaintext)` and feed
/// the outcome into [`decide_state_from_open`]. This split keeps the
/// pure decision logic separate from the impure `open` call so each
/// branch is unit-testable without touching the filesystem.
#[must_use]
pub fn decide_state_from_inspect(
    path: &Path,
    inspect: Result<VaultStatus, PaladinError>,
) -> Option<AppState> {
    match inspect {
        Ok(VaultStatus::Missing) => Some(AppState::MissingVault {
            path: path.to_path_buf(),
        }),
        Ok(VaultStatus::Encrypted) => Some(AppState::Unlock {
            path: path.to_path_buf(),
            error: None,
            passphrase: PassphraseBuffer::new(),
        }),
        Ok(VaultStatus::Plaintext) => None,
        Err(err) => Some(AppState::StartupError {
            path: Some(path.to_path_buf()),
            message: render_error_message(&err),
        }),
    }
}

/// Map a `Store::open` result onto the corresponding initial
/// [`AppState`].
///
/// `now` is the monotonic instant sampled at the boundary (right
/// after `Store::open` returns) and is used to compute the auto-lock
/// [`AppState::Unlocked::idle_deadline`] via
/// [`compute_idle_deadline`]. It is unused on the error branch.
#[must_use]
pub fn decide_state_from_open(
    now: Instant,
    path: PathBuf,
    open: Result<(Vault, Store), PaladinError>,
) -> AppState {
    match open {
        Ok((vault, store)) => {
            let idle_deadline = compute_idle_deadline(now, &vault);
            let selected = initial_selection(&vault);
            AppState::Unlocked {
                path,
                vault,
                store,
                search_query: String::new(),
                idle_deadline,
                pending_clipboard_clear: None,
                hotp_reveal: None,
                modal: None,
                selected,
                pending_chord_leader: None,
                viewport_height: 0,
                viewport_offset: 0,
                focus: Focus::List,
                status_line: None,
                help_open: false,
            }
        }
        Err(err) => AppState::StartupError {
            path: Some(path),
            message: render_error_message(&err),
        },
    }
}

/// Compute the initial `AppState::Unlocked::selected` for `vault`.
///
/// Mirrors [`paladin_core::select_after_filter`] for `prev = None` and
/// the empty-search filtered set (`Vault::iter()` in insertion
/// order): the first account when one exists, `None` when the vault
/// is empty. Used on every Unlocked-entry site so the user lands on
/// a navigable selection without an extra arrow-key press.
#[must_use]
pub fn initial_selection(vault: &Vault) -> Option<AccountId> {
    vault.iter().next().map(paladin_core::Account::id)
}

/// Compute the auto-lock idle deadline for the given vault at `now`.
///
/// Thin wrapper around [`paladin_core::IdlePolicy::next_deadline`]
/// that pulls `is_encrypted` and `settings()` off the [`Vault`] so
/// every Unlocked-entry site uses the same call shape. Returns
/// `None` for plaintext vaults (the §6 / §7 plaintext-no-op rule)
/// and for encrypted vaults whose `auto_lock_enabled` setting is
/// `false`; otherwise returns `Some(now + timeout)`.
#[must_use]
pub fn compute_idle_deadline(now: Instant, vault: &Vault) -> Option<Instant> {
    IdlePolicy::next_deadline(now, vault.is_encrypted(), vault.settings())
}

/// Render an error for the startup-error screen.
///
/// `unsafe_permissions` errors use the `Some(text)` from
/// [`paladin_core::format_unsafe_permissions`] verbatim so the CLI,
/// TUI, and GUI surface identical wording; every other error falls
/// back to the error's `Display` implementation.
#[must_use]
pub fn render_error_message(error: &PaladinError) -> String {
    format_unsafe_permissions(error).unwrap_or_else(|| error.to_string())
}

/// Build the TUI's initial state from the optional `--vault`
/// command-line override.
///
/// Mirrors `IMPLEMENTATION_PLAN_03_TUI.md` "Startup / vault modes":
///
/// 1. Resolve the vault path (`--vault` overrides `default_vault_path`).
/// 2. Call [`paladin_core::inspect`].
/// 3. Branch on [`VaultStatus`]; plaintext vaults are opened
///    immediately, encrypted vaults defer to the unlock screen,
///    missing vaults open the guidance screen, and any error from
///    path resolution / `inspect` / plaintext `open` lands on the
///    non-mutating startup-error screen.
pub fn build_initial_state(vault: Option<PathBuf>) -> AppState {
    let path: PathBuf = match vault {
        Some(p) => p,
        None => match paladin_core::default_vault_path() {
            Ok(p) => p,
            Err(err) => {
                return AppState::StartupError {
                    path: None,
                    message: render_error_message(&err),
                };
            }
        },
    };

    let inspect = paladin_core::inspect(&path);
    if let Some(state) = decide_state_from_inspect(&path, inspect) {
        return state;
    }
    // `VaultStatus::Plaintext` — open immediately, no passphrase prompt.
    let open = Store::open(&path, VaultLock::Plaintext);
    // Sample `now` at the boundary so the auto-lock deadline math
    // sees the same instant the open completed at. For plaintext
    // vaults the deadline is always `None`; the sample is still
    // taken to keep the call shape uniform with encrypted unlock.
    let now = Instant::now();
    decide_state_from_open(now, path, open)
}
